import Head from 'next/head'
import Layout from "../components/layout";
import useTranslation from 'next-translate/useTranslation';

export default function Home() {
  const { t } = useTranslation();

  return (
    <div >
      <Head>
        <title>i18n</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Layout>
          <h1>{t("common:greeting")}</h1>
        </Layout>
     
    </div>
  )
}
